#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.query_logging = 1
    args.enable_dhcp = 0

    # ------------
    # Tests to run
    # ------------

    [default.test_upgrade_from.3d2f68c4e19f335e63f8ffa259708b38a58c8f67]
    name = "5.11.4~ynh1"
    args.admin = "package_checker"

    [default.test_upgrade_from.4999654987af8b1427a6c72f8af482b235bb46db]
    name = "Merge pull request #88"
    args.admin = "package_checker"



    # ; Config_panel
    #     main.overwrite_files.overwrite_setupvars=0|1
    #     main.overwrite_files.overwrite_ftl=0|1
    #     main.overwrite_files.overwrite_nginx=0|1
    #     main.overwrite_files.overwrite_phpfpm=0|1
    #     main.global_config.email_type=0|1
    #     main.php_fpm_config.footprint=low|medium|high
    #     main.php_fpm_config.free_footprint=20
    #     main.php_fpm_config.usage=low|medium|high
    #     main.php_fpm_config.force_max_children=20|0

        # actions=0
        # config_panel=0
