#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.query_logging = 1
    args.enable_dhcp = 0

    # ------------
    # Tests to run
    # ------------

    [default.test_upgrade_from.5cc0fe9d7586001602bbaf87084c0ddbbaa041a6]
    name = "Last packagingv1 version"
    args.admin = "package_checker"
    args.domain = "domain.tld"

    # ; Config_panel
    #     main.overwrite_files.overwrite_setupvars=0|1
    #     main.overwrite_files.overwrite_ftl=0|1
    #     main.overwrite_files.overwrite_nginx=0|1
    #     main.overwrite_files.overwrite_phpfpm=0|1
    #     main.global_config.email_type=0|1
    #     main.php_fpm_config.footprint=low|medium|high
    #     main.php_fpm_config.free_footprint=20
    #     main.php_fpm_config.usage=low|medium|high
    #     main.php_fpm_config.force_max_children=20|0

        # actions=0
        # config_panel=0
